DROP TABLE IF EXISTS likes, friendship, film_genre, users, genres, film_director, directors, like_reviews, reviews, films, mpa;

CREATE TABLE IF NOT EXISTS app_users(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email VARCHAR(50) NOT NULL,
login VARCHAR(60) NOT NULL,
name VARCHAR(30),
birthday DATE NOT NULL);

CREATE TABLE IF NOT EXISTS films(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title VARCHAR(60) NOT NULL,
description VARCHAR(200),
releaseDate DATE NOT NULL,
duration INTEGER,
mpa_id INTEGER);

CREATE TABLE IF NOT EXISTS genres(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50));

CREATE TABLE IF NOT EXISTS mpa(
mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
rating VARCHAR(10));

CREATE TABLE IF NOT EXISTS film_genre(
film_id INTEGER,
genre_id INTEGER,
FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE,
PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes(
film_id INTEGER,
user_id INTEGER,
FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE,
PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends(
user_id INTEGER,
friend_id INTEGER,
FOREIGN KEY (friend_id) REFERENCES app_users (id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE,
PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS reviews(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
content VARCHAR(200),
is_positive BOOLEAN,
user_id INTEGER,
film_id INTEGER,
useful INTEGER
);

CREATE TABLE IF NOT EXISTS like_reviews (
    review_id INT REFERENCES reviews(id) ON DELETE CASCADE,
    user_id INT REFERENCES app_users(id) ON DELETE CASCADE,
    is_like BOOLEAN
);

CREATE TABLE IF NOT EXISTS directors
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS film_director
(
    film_id     INTEGER,
    director_id INTEGER,
    CONSTRAINT film_director_film_id_fk FOREIGN KEY (film_id) REFERENCES films,
    CONSTRAINT film_director_director_id_fk FOREIGN KEY (director_id) REFERENCES directors,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);

CREATE TABLE IF NOT EXISTS event_type (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS operation (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_name VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS feed (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id INT,
    timestamp BIGINT,
    user_id INT REFERENCES app_users(id) ON DELETE CASCADE,
    event_type_id INT REFERENCES event_type(id) ON DELETE CASCADE,
    operation_id INT REFERENCES operation(id) ON DELETE CASCADE
);
